site_name: fiware-cosmos
site_url: https://fiware-cosmos.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-cosmos.git
site_description: Cosmos Documentation
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
google_analytics: ['UA-84812269-1', 'fiware-cosmos.readthedocs.io']
pages:
  - Home: index.md
  - 'Quick Start Guide': 'quick_start_guide_new.md'
  - 'User and Programmer manual':
      - 'Introduction': 'user_and_programmer_manual/introduction.md'
      - 'Using the GUI': 'user_and_programmer_manual/using_gui.md'
      - 'OAuth2 in Cosmos APIs': 'user_and_programmer_manual/using_oauth2.md'
      - 'Data management and I/O': 'user_and_programmer_manual/data_management_and_io.md'
      - 'Requesting computing resources': 'user_and_programmer_manual/request_computing_resources.md'
      - 'Using Tidoop': 'user_and_programmer_manual/using_tidoop.md'
      - 'Using Hadoop and its ecosystem': 'user_and_programmer_manual/using_hadoop_and_ecosystem.md'
