site_name: fiware-cosmos
site_url: https://fiware-cosmos.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-cosmos.git
site_description: Cosmos Documentation
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["http://fiware.org/style/monokai_sublime.css"]
pages:
  - Home: rtfd_home.md
  - 'User and Programmer manual':
      - 'Introduction': 'user_and_programmer_manual/introduction.md'
      - 'Data management and I/O': 'user_and_programmer_manual/batch/data_management_and_io.md'
      - 'Requesting computing resources': 'user_and_programmer_manual/batch/request_computing_resources.md'
      - 'Using Hadoop': 'user_and_programmer_manual/batch/using_hadoop.md'
      - 'OAuth2-protected REST APIs': 'user_and_programmer_manual/batch/oauth2_rest_apis.md'
  - 'Installation and Administration manual':

