site_name: fiware-cosmos
site_url: https://fiware-cosmos.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-cosmos.git
site_description: Cosmos Documentation
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["http://fiware.org/style/monokai_sublime.css"]
pages:
  - Home: rtfd_home.md
  - 'User and Programmer manual':
      - 'Introduction': 'user_and_programmer_manual/introduction.md'
      - 'Data management and I/O': 'user_and_programmer_manual/batch/data_management_and_io.md'
      - 'Requesting computing resources': 'user_and_programmer_manual/batch/request_computing_resources.md'
      - 'Using Hadoop and its ecosystem': 'user_and_programmer_manual/batch/using_hadoop_and_ecosystem.md'
      - 'OAuth2-protected REST APIs': 'user_and_programmer_manual/batch/oauth2_rest_apis.md'
  - 'Installation and Administration manual':
      - 'Some words about Cosmos and its ecosystem': 'installation_and_administration_manual/some_words_about_cosmos_and_ecosystem.md'
      - 'HAAS engine (Shara version)': 'installation_and_administration_manual/haas_engine_sahara.md'
      - 'HAAS engine (shared Hadoop version)': 'installation_and_administration_manual/haas_engine_shared_hadoop.md'
      - 'Storage cluster': 'installation_and_administration_manual/storage_cluster.md'
      - 'Cosmos GUI': 'installation_and_administration_manual/cosmos_gui.md'
      - 'OAuth2-protected APIs': 'installation_and_administration_manual/oauth2_protected_apis.md'
      - 'Tidoop': 'installation_and_administration_manual/tidoop.md'
      - 'Cygnus': 'installation_and_administration_manual/cygnus.md'
      - 'Sanity Check Procedures': 'installation_and_administration_manual/sanity_check_procedures.md'
      - 'Diagnosis Procedures': 'installation_and_administration_manual/diagnosis_procedures.md'
      - 'Annex A: Creating a public-private key pair and installing the public key': 'installation_and_administration_manual/annex_a_create_and_install_keypair.md'
      - 'Annex B: Get a keystone auth token': 'installation_and_administration_manual/annex_b_get_keystone_auth_token.md'
